//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkout {
    
    
    public partial class PaymentOptionsXML {
        
        /// <summary>
        /// MerchantAndBuyerInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkout.User_Controls.MerchantAndBuyerInfo MerchantAndBuyerInfo;
        
        /// <summary>
        /// BankPaymentOptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkout.User_Controls.BankPaymentOptions BankPaymentOptions;
        
        /// <summary>
        /// PaymentURL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkout.User_Controls.PaymentURL PaymentURL;
        
        /// <summary>
        /// CheckoutFinlandInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkout.User_Controls.CheckoutFinlandInfo CheckoutFinlandInfo;
        
        /// <summary>
        /// checkoutFinlandContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal checkoutFinlandContact;
        
        /// <summary>
        /// PreviousPage property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Checkout.PaymentWebForm PreviousPage {
            get {
                return ((Checkout.PaymentWebForm)(base.PreviousPage));
            }
        }
    }
}
